version: "3"

services:

  db:
    image: postgres:14-alpine
    container_name: db_sales_network_container
    environment:
      PGDATA: /var/lib/postgresql/pgdata
      POSTGRES_DB: sales_network
      POSTGRES_PASSWORD: sales_network_password
    volumes:
      - postgres_data_sales_network:/var/lib/postgresql/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app_sales_network_container
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env

volumes:
  postgres_data_sales_network: