# Generated by Django 4.2.5 on 2023-10-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='entity_email')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='entity_phone')),
                ('country', models.CharField(max_length=100, verbose_name='entity_country')),
                ('city', models.CharField(max_length=100, verbose_name='entity_city')),
                ('street', models.CharField(max_length=100, verbose_name='entity_street')),
                ('building', models.IntegerField(verbose_name='entity_building_number')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='factory_name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factory_contacts', to='sales_network.contactinfo')),
            ],
            options={
                'verbose_name': 'Factory',
                'verbose_name_plural': 'Factories',
            },
        ),
        migrations.CreateModel(
            name='MainNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_network_contacts', to='sales_network.contactinfo')),
                ('products', models.ManyToManyField(blank=True, related_name='main_networks_products', to='products.product')),
            ],
            options={
                'verbose_name': 'Main Network',
                'verbose_name_plural': 'Main Networks',
            },
        ),
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='network_name')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='debt_to_supplier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_contacts', to='sales_network.contactinfo')),
                ('factory_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier', to='sales_network.factory', verbose_name='supplier')),
                ('main_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_network_retail_net', to='sales_network.mainnetwork', verbose_name='main_network')),
                ('products', models.ManyToManyField(blank=True, related_name='network_products', to='products.product')),
            ],
            options={
                'verbose_name': 'Retail Network',
                'verbose_name_plural': 'Retail Networks',
            },
        ),
        migrations.CreateModel(
            name='SoleProprietor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='proprietor_name')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='debt_to_supplier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proprietor_contacts', to='sales_network.contactinfo')),
                ('factory_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_supplier_for_proprietor', to='sales_network.factory', verbose_name='factory_supplier')),
                ('main_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_network_proprietor', to='sales_network.mainnetwork', verbose_name='main_network')),
                ('products', models.ManyToManyField(blank=True, related_name='proprietor_products', to='products.product')),
                ('retail_network_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_network_supplier', to='sales_network.retailnetwork', verbose_name='retail_network_supplier')),
            ],
            options={
                'verbose_name': 'Sole Proprietor',
                'verbose_name_plural': 'Sole Proprietors',
            },
        ),
        migrations.AddField(
            model_name='factory',
            name='main_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_network_factory', to='sales_network.mainnetwork', verbose_name='main_network'),
        ),
        migrations.AddField(
            model_name='factory',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='factory_products', to='products.product'),
        ),
    ]
