# Generated by Django 4.2.5 on 2023-10-03 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='entity_email')),
                ('phone', models.CharField(max_length=20, verbose_name='entity_phone')),
                ('country', models.CharField(max_length=100, verbose_name='entity_country')),
                ('city', models.CharField(max_length=100, verbose_name='entity_city')),
                ('street', models.CharField(max_length=100, verbose_name='entity_street')),
                ('building', models.IntegerField(verbose_name='entity_building_number')),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='factory_name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factory_contacts', to='sales_network.contactinfo')),
                ('products', models.ManyToManyField(related_name='factory_products', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='network_name')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='debt_to_supplier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_contacts', to='sales_network.contactinfo')),
                ('factory_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_supplier', to='sales_network.factory', verbose_name='factory_supplier')),
                ('products', models.ManyToManyField(related_name='network_products', to='products.product')),
            ],
        ),
    ]
