# Generated by Django 4.2.5 on 2023-10-03 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0002_soleproprietor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailnetwork',
            name='factory_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_supplier', to='sales_network.factory', verbose_name='network_supplier'),
        ),
    ]
