# Generated by Django 4.2.5 on 2023-10-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales_network', '0003_alter_retailnetwork_factory_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Contact Information', 'verbose_name_plural': 'Contact Information'},
        ),
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name': 'Factory', 'verbose_name_plural': 'Factories'},
        ),
        migrations.AlterModelOptions(
            name='retailnetwork',
            options={'verbose_name': 'Retail Network', 'verbose_name_plural': 'Retail Networks'},
        ),
        migrations.AlterModelOptions(
            name='soleproprietor',
            options={'verbose_name': 'Sole Proprietor', 'verbose_name_plural': 'Sole Proprietors'},
        ),
        migrations.AlterField(
            model_name='factory',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='factory_products', to='products.product'),
        ),
        migrations.AlterField(
            model_name='retailnetwork',
            name='debt_to_supplier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='debt_to_supplier'),
        ),
        migrations.AlterField(
            model_name='retailnetwork',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='network_products', to='products.product'),
        ),
        migrations.AlterField(
            model_name='soleproprietor',
            name='debt_to_supplier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='debt_to_supplier'),
        ),
        migrations.AlterField(
            model_name='soleproprietor',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='proprietor_products', to='products.product'),
        ),
    ]
