# Generated by Django 4.2.5 on 2023-10-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales_network', '0004_alter_contactinfo_options_alter_factory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailnetwork',
            name='debt_to_supplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='debt_to_supplier'),
        ),
        migrations.AlterField(
            model_name='retailnetwork',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='network_products', to='products.product'),
        ),
        migrations.AlterField(
            model_name='soleproprietor',
            name='debt_to_supplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='debt_to_supplier'),
        ),
        migrations.AlterField(
            model_name='soleproprietor',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='proprietor_products', to='products.product'),
        ),
    ]
