# Generated by Django 4.2.5 on 2023-10-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales_network', '0005_alter_retailnetwork_debt_to_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='factory_products', to='products.product'),
        ),
    ]
