# Generated by Django 4.2.5 on 2023-10-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0008_alter_retailnetwork_factory_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailnetwork',
            name='debt_to_supplier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='debt_to_supplier'),
        ),
        migrations.AlterField(
            model_name='soleproprietor',
            name='debt_to_supplier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='debt_to_supplier'),
        ),
    ]
