# Generated by Django 4.2.5 on 2023-10-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales_network', '0009_alter_retailnetwork_debt_to_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_network_contacts', to='sales_network.contactinfo')),
                ('products', models.ManyToManyField(to='products.product', verbose_name='main_network_products')),
            ],
            options={
                'verbose_name': 'Main Network',
                'verbose_name_plural': 'Main Networks',
            },
        ),
        migrations.AddField(
            model_name='factory',
            name='main_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_network.mainnetwork', verbose_name='main_network'),
        ),
        migrations.AddField(
            model_name='retailnetwork',
            name='main_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_network.mainnetwork', verbose_name='main_network'),
        ),
        migrations.AddField(
            model_name='soleproprietor',
            name='main_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_network.mainnetwork', verbose_name='main_network'),
        ),
    ]
