# Generated by Django 4.2.5 on 2023-10-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales_network', '0010_mainnetwork_factory_main_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='main_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_network.mainnetwork', verbose_name='main_network'),
        ),
        migrations.AlterField(
            model_name='mainnetwork',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product', verbose_name='main_network_products'),
        ),
        migrations.AlterField(
            model_name='retailnetwork',
            name='main_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_network.mainnetwork', verbose_name='main_network'),
        ),
        migrations.AlterField(
            model_name='soleproprietor',
            name='main_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_network.mainnetwork', verbose_name='main_network'),
        ),
    ]
