# Generated by Django 4.2.5 on 2023-10-06 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0011_alter_factory_main_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soleproprietor',
            name='retail_network_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_network_supplier', to='sales_network.retailnetwork', verbose_name='retail_network_supplier'),
        ),
    ]
