# Generated by Django 4.2.5 on 2023-10-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0012_alter_soleproprietor_retail_network_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='entity_email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='entity_phone'),
        ),
    ]
