# Generated by Django 4.2.5 on 2023-10-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0014_alter_soleproprietor_factory_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
