# Generated by Django 4.2.5 on 2023-10-09 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0015_contactinfo_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soleproprietor',
            name='factory_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_supplier_for_proprietor', to='sales_network.factory', verbose_name='factory_supplier'),
        ),
    ]
