# Generated by Django 4.2.5 on 2023-10-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name'),
        ('sales_network', '0016_alter_soleproprietor_factory_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainnetwork',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='main_networks_products', to='products.product'),
        ),
    ]
