# Generated by Django 4.2.5 on 2023-10-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0017_alter_mainnetwork_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='main_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_network_factory', to='sales_network.mainnetwork', verbose_name='main_network'),
        ),
        migrations.AlterField(
            model_name='retailnetwork',
            name='main_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_network_retail_net', to='sales_network.mainnetwork', verbose_name='main_network'),
        ),
        migrations.AlterField(
            model_name='soleproprietor',
            name='main_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_network_proprietor', to='sales_network.mainnetwork', verbose_name='main_network'),
        ),
    ]
