# Generated by Django 4.2.5 on 2023-10-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='launch_date',
            field=models.DateField(verbose_name='product_launch_date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='product_name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.CharField(max_length=50, verbose_name='product_model'),
        ),
    ]
